model:
  name: "linear_attention"         # Model type to use as backbone
  dim: 256            # Model embedding dimension
  num_layers: 2       # Number of layers in the model

training:
  batch_size: 4       # Batch size for training and evaluation
  epochs: 10           # Number of training epochs
  sequence_length: 1024 # Maximum sequence length
  learning_rate: 1e-6 # Learning rate for optimizer

hardware:
  device: "cuda"      # Device to run on (cuda/cpu)

benchmark:
  name: "memcopy"     # Options: lambada, wikitext, memcopy, lra

logging:
  project_name: "language_model_benchmarks"
  